### ISSUE TITLE
Chrono Trigger (USA) Header problem.

### ISSUE THREAD

**Issue by ghost** [Mr-Berzerk/PSXtract2021#1]
Hello there Mr-Berzerk, thank you for updating this great tool,
Question not sure how this can be used: 
https://github.com/DeadlySystem/isofix
If i select the ISO.BIN and ISO_HEADER.BIN seems to correct the image but still encrypted, ends up replacing the ISO_HEADER.BIN with full size of the ISO.BIN (CRC changes)
So not sure how to tell pxpextract to use the new fixed file instead or to decrypt it.
If i leave all the files and redo the command, all files get extracted again so is everything from the beginning.
This is the only game from my small collection that doesn't convert properly.
Ends up as 187 mbs bin, when emulated there's no videos, cmd reports ERROR about the header.
![Screenshot 2021-12-07 193242](https://user-images.githubusercontent.com/69441718/145132860-7e4a24c3-59cc-4ffb-9467-762ae725c467.png)
![Screenshot 2021-12-07 193314](https://user-images.githubusercontent.com/69441718/145132859-7db04dea-bc90-44b3-a9a5-be5b4c626328.png)
![Screenshot 2021-12-07 193406](https://user-images.githubusercontent.com/69441718/145132857-5fbdbe4e-e128-4751-b910-27941eb80061.png)
![Screenshot 2021-12-07 193443](https://user-images.githubusercontent.com/69441718/145132855-c73d9273-c68b-4cf9-9062-043d6b7b02c5.png)

**Comment by Mr-Berzerk** [comment]
Hey SA-X0, thanks for the question. Sorry I've not responded sooner. Been busy with end of year/Christmas work. 
If I understand the issue right, you have extracted the Chrono_Trigger.pbp to ISO.bin file using the PSXtract2021, and then are trying to have it work in a PS1 emulator? Does it properly extract the .cue file?
Sorry I'm a little lost at what point things break down.

**Comment by SA-X0** [comment]
No worries and happy Holidays Mr-Berzerk.
Basically as you see on the screenshots fails to rebuild the iso due to the header, which by the link i provided is suppose to fix it?
So the game works but is not a good iso, there's no videos, Japanese version has no problems and final size is around 600mbs while the US version due to failing is only 192mbs.
Main point was that the tool still fails with this particular title Chrono Trigger (USA) it can't rebuild it properly.

**Comment by Mr-Berzerk** [comment]
From the reading I've been doing, some times the videos don't work depending on the OS being used, and the video codec (PAL vs NTSC). Have you tried different OS roms/changing the video spec?
